### ISSUE TITLE
Error when no ".env" file is present

### ISSUE THREAD

**Issue by gEndelf** [nwinch/webpack-dotenv-plugin#12]
I get the following error when a .env file is not present, but the variables are still available in the environment:

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at new DotenvPlugin (/develop/prj/mot-admin-react/node_modules/webpack-dotenv-plugin/index.js:14:30)
    at Object.<anonymous> (webpack.config.dev.js:27:5)
    at Module._compile (module.js:556:32)
    at loader (/develop/prj/mot-admin-react/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/develop/prj/mot-admin-react/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (srcServer.js:12:1)
    at Module._compile (module.js:556:32)
    at loader (/develop/prj/mot-admin-react/node_modules/babel-register/lib/node.js:148:5)
```

I think if "silent: true" was defined for dotenv-safe plugin should not check .env file for availablity

**Comment by hassankhan** [comment]
This kind of ruins the whole point of `dotenv`, our CI passes the environment variables but locally we have `.env` files. IIRC, committing `.env` files is an antipattern (could be wrong)

**Comment by nwinch** [comment]
Thanks @gEndelf.  It would be simple enough to add a flag which governs the existence of a `.env` file or not, but this would then allow bypassing any `dotenv` checks/warnings which is one of the purpose of the plugin.

@hassankhan Regarding CI and different environments - you are correct, you should not commit a `.env` file with your codebase.  One alternative is to dynamically generate a `.env` file with those environments before bundles are built so you're build pipeline continues to consistently use/enforce `dotenv` where it's used e.g testing, staging, production etc..

If we were to allow the option of silencing, then any missed or misconfigured environment variables would only be detected once in the built environment e.g app is now broken in staging because someone forgot to add `ENV_X` to the staging build pipeline.

**Comment by rolodato** [comment]
FYI if you update to the latest version of dotenv-safe, you won't be seeing this problem. With the newest changes, if you have a missing .env file but all required variables are present, no exception will be thrown but you'll get an `error` property in the result object returned by `load()` with the details of the error.

**Comment by nwinch** [comment]
Thanks @rolodato I'll look at upgrading 👍

**Comment by myaskevich** [comment]
@rolodato thanks for the tip, but how? `dotenv-safe` is a transitive dependency of `webpack-dotenv-plugin` that I cannot take control of.

**Comment by rolodato** [comment]
@myaskevich As you mentioned, `webpack-dotenv-plugin` will need to update its `dotenv-safe` dependency. By glancing at the code I think the package.json could be updated directly to the latest version of `dotenv-safe` without needing to change anything else, so if you're up for a pull request that would work.

The alternative would be to fork `webpack-dotenv-plugin` and depend on the fork from your application, but for such a simple change it doesn't seem to make sense.

**Comment by mayask** [comment]
Yeah,
I just didn't get @nwinch is one of the contribs ;)
I'll send a PR in an hour, if you don't mind

**Comment by rolodato** [comment]
Cool! I'm not familiar with this library (or webpack at all, for that matter) but let me know here if you run into any issues specific to `dotenv-safe`.
